package constants;

public class DBConstants {	
	
	/* Export queries*/
	public static String GET_TRANS_E_RTWGRN="SELECT distinct(TRANSID) FROM TL_E_RTWGRN WHERE PROCESSFLAG='0' order by TRANSID";
	public static String GET_TRANS_E_LOADSHIP="SELECT distinct(TRANSID) FROM TL_E_LOADSHIP WHERE PROCESSFLAG='0' order by TRANSID";
	public static String GET_TRANS_E_LOADSHIP_ERTL="SELECT distinct(TRANSID) FROM TL_E_LOADSHIP_ERTL WHERE PROCESSFLAG='0'";
	public static String GET_TRANS_E_ZSTAMSG="SELECT distinct(TRANSID) FROM TL_E_RTWGRN WHERE PROCESSFLAG='0'";
	public static String GET_TRANS_E_RTVSHIPMENT="SELECT distinct(TRANSID) FROM TL_E_RTVSHIPMENT WHERE PROCESSFLAG='0' order by TRANSID";
	public static String GET_TRANS_E_INVMV="SELECT distinct(TRANSID) FROM TL_E_INVMOVE WHERE PROCESSFLAG='0' order by TRANSID";
	public static String GET_TRANS_E_ASNGRN="SELECT distinct(TRANSID) FROM TL_E_ASNGRN WHERE PROCESSFLAG='0' order by TRANSID";
	public static String GET_TRANS_E_INVCHNG="SELECT distinct(TRANSID) FROM TL_E_INVMOVE WHERE PROCESSFLAG='0' order by TRANSID";
	public static String GET_TRANS_E_LOADSHIP_ERTL_WS="SELECT distinct(TRANSID) FROM TL_E_LOADSHIP_ERTL_WS WHERE PROCESSFLAG='0'";
	public static String GET_TRANS_E_ZWS_GRPOVAPI="SELECT distinct(TRANSID) FROM TL_E_ASNGRN_WS WHERE PROCESSFLAG='0' order by TRANSID";
	public static String GET_TRANS_E_ASNGRN_ECOMGR="SELECT distinct(TRANSID) FROM TL_E_ASNGRN_ECOMGR WHERE PROCESSFLAG='0' order by TRANSID";
	public static String GET_TRANS_E_RFIDSKU="SELECT distinct(TRANSID) FROM tl_e_WSRFIDITEM WHERE PROCESSFLAG='0'";
	public static String GET_TRANS_E_RFIDASN="SELECT distinct(TRANSID) FROM tl_e_WSRFIDASN WHERE PROCESSFLAG='0'";
	public static String GET_TRANS_E_RFIDASNCLOSE="SELECT distinct(TRANSID) FROM tl_e_WSRFIDASNCLOSE WHERE PROCESSFLAG='0'";
	public static String GET_TRANS_E_RFIDLOC = "SELECT distinct(TRANSID) FROM TL_E_WSRFIDLOCATION WHERE PROCESSFLAG='0'";
	public static String GET_TRANS_E_ASNGRN_WD30="SELECT distinct(TRANSID) FROM TL_E_ASNGRN_WD30 WHERE PROCESSFLAG='0' order by TRANSID";
	
	public static String GET_TL_E_RTWGRN_HEADER="select distinct RTW.WHSEID,RTW.ASNNO,RTW.STANO,RTW.ASNTYPE,RTW.GRNDAT,RTW.PLANT from TL_E_RTWGRN RTW where TRANSID=?";
	public static String GET_TL_E_LOADSHIP_HEADER="select distinct HL,LOADID,LOADDATE,WHSEID from TL_E_LOADSHIP where TRANSID=?";
	public static String GET_TL_E_RTVSHIPMENT_HEADER="select distinct HL,EBELN,LOADID,GRNDAT,LRNO,VENDINV,WHSEID from TL_E_RTVSHIPMENT where TRANSID=?";
	public static String GET_TL_E_ASNGRN_HEADER="select distinct HL,EBELN,ASNNO,GRNDAT,LRNO,VENDINV,WHSEID from TL_E_ASNGRN where TRANSID=?";
	public static String GET_TL_E_ZSTAMSG_HEADER="select RTW.WHSEID,RTW.ASNNO,RTW.STANO,RTW.ASNTYPE,RTW.GRNDAT,RTW.PLANT from TL_E_RTWGRN RTW where TRANSID=?";
	public static String GET_TL_E_LOADSHIP_ERTL_HEADER="select HL,LOADID,LOADDATE,WHSEID from TL_E_LOADSHIP_ERTL where TRANSID=?";
	public static String GET_TL_E_LOADSHIP_ERTL_WS_HEADER="select HL,LOADID,LOADDATE,WHSEID from TL_E_LOADSHIP_ERTL_WS where TRANSID=?";
	public static String GET_TL_E_ZWS_GRPOVAPI_HEADER="select distinct HL,EBELN,ASNNO,GRNDAT,LRNO,VENDINV,WHSEID from TL_E_ASNGRN_WS where TRANSID=?";
	public static String GET_TL_E_ASNGRN_ECOMGR_HEADER="select distinct HL,EBELN,ASNNO,GRNDAT,LRNO,VENDINV,WHSEID from TL_E_ASNGRN_ECOMGR where TRANSID=?";
	public static String GET_TL_E_RFIDSKU_HEADER ="select distinct trunc(adddate) as ADDDATE ,WHSEID,STORERKEY from TL_E_WSRFIDITEM where TRANSID=?";
	public static String GET_TL_E_RFIDASN_HEADER ="select distinct trunc(adddate) as ADDDATE ,WHSEID,RECEIPTKEY,EXTERNRECEIPTKEY from tl_e_WSRFIDASN where TRANSID=?";
	public static String GET_TL_E_RFIDASNCLOSE_HEADER ="select distinct trunc(adddate) as ADDDATE ,WHSEID,RECEIPTKEY from tl_e_WSRFIDASNCLOSE where TRANSID=?";
	public static String GET_TL_E_RFIDLOC_HEADER = "select distinct trunc(adddate) as ADDDATE ,WHSEID,STORERKEY from TL_E_WSRFIDLOCATION where TRANSID=?";
	public static String GET_TL_E_ASNGRN_WD30_HEADER="select HL,EBELN,ASNNO,GRNDAT,LRNO,VENDINV,WHSEID from TL_E_ASNGRN_WD30 where TRANSID=?";
	
	public static String GET_TL_E_RTWGRN_DATA="select distinct RTW.VBELN,RTW.EXLINENO,RTW.Item,RTW.QTY,RTW.LGORT from TL_E_RTWGRN RTW where TRANSID=?";
	public static String GET_TL_E_LOADSHIP_DATA="select distinct HL,EBELN,EBELP,MATNR,MENGE,LPNNO,MSTCARTON from TL_E_LOADSHIP where TRANSID=?";
	public static String GET_TL_E_RTVSHIPMENT_DATA="select distinct EBELN,EBELP,MATNR,MENGE,WERKS,LGORT,CONDITIONCODE from TL_E_RTVSHIPMENT where TRANSID=?";
	public static String GET_TL_E_ASNGRN_DATA="select distinct HL,EBELN,EBELP,MATNR,MENGE,WERKS,LGORT,CONDITIONCODE,R_WERKS,LPN from TL_E_ASNGRN where TRANSID=?";
	public static String GET_TL_E_ZINVMVMSG_DATA="select distinct WHSEID,HL,WAREHOUSE,ARTICLE,FROMLOC,TOLOC,QTY,MVDAT from TL_E_INVMOVE where TRANSID=?";
	public static String GET_TL_E_INVCHNG_DATA="select distinct WHSEID,EBELN,MATNR,LPN,WERKS,LGORT,R_WERKS from TL_E_INVMOVE where TRANSID= ";
	public static String GET_TL_E_ZSTAMSG_DATA="select RTW.VBELN,RTW.EXLINENO,RTW.Item,RTW.QTY from TL_E_RTWGRN RTW where TRANSID=?";
	public static String GET_TL_E_LOADSHIP_ERTL_DATA="select HL,EBELN,EBELP,MATNR,MENGE,LPNNO,MSTCARTON from TL_E_LOADSHIP_ERTL where TRANSID=?";
	public static String GET_TL_E_LOADSHIP_ERTL_WS_DATA="select HL,EBELN,EBELP,MATNR,MENGE,LPNNO,MSTCARTON from TL_E_LOADSHIP_ERTL_WS where TRANSID=?";
	public static String GET_TL_E_ZWS_GRPOVAPI_DATA="select distinct HL,EBELN,EBELP,MATNR,MENGE,WERKS,LGORT,CONDITIONCODE,R_WERKS,LPN from TL_E_ASNGRN_WS where TRANSID=?";
	public static String GET_TL_E_ASNGRN_ECOMGR_DATA="select distinct HL,EBELN,EBELP,MATNR,MENGE,WERKS,LGORT,CONDITIONCODE,R_WERKS,LPN from TL_E_ASNGRN_ECOMGR where TRANSID=?";
	public static String GET_TL_E_RFIDSKU_DATA="select distinct WHSEID as \"WHSEID\",STORERKEY as \"StorerKey\",SKU as \"Sku\",DESCR as \"Descr\",ALTSKU as \"AltSku\" from TL_E_WSRFIDITEM  where TRANSID=?";
	public static String GET_TL_E_RFIDASN_DATA="select distinct RECEIPTLINENUMBER as \"ReceiptLineNumber\",STORERKEY as \"StorerKey\" ,SKU as \"Sku\",QTYEXPECTED as \"QtyExpected\" from tl_e_WSRFIDASN  where TRANSID=?";
	public static String GET_TL_E_RFIDASNCLOSE_DATA="select distinct ReceiptKey as \"ReceiptKey\",WHSEID as \"WHSEID\",STATUS as \"STATUS\" from tl_e_WSRFIDASNCLOSE where TRANSID=?";
	public static String GET_TL_E_RFIDLOC_DATA = "select distinct WHSEID as \"WHSEID\",STORERKEY as \"StorerKey\",LOC as \"LOC\" from TL_E_WSRFIDLOCATION  where TRANSID=?";
	public static String GET_TL_E_ASNGRN_WD30_DATA="select HL, EBELN, EBELP, MATNR, MENGE, WERKS, LGORT, CONDITIONCODE,R_WERKS,LPN from TL_E_ASNGRN_WD30 where TRANSID=?";
	
	
	public static String GET_TL_E_RTWGRN_UPDT="UPDATE TL_E_RTWGRN RTW SET PROCESSFLAG='9' , FILENAME=?,PROCESSDATE=sysdate where TRANSID= ?";
	public static String GET_TL_E_ZINVMVMSG_UPDT="UPDATE TL_E_INVMOVE SET PROCESSFLAG='9' , FILENAME=?,PROCESSDATE=sysdate where TRANSID= ?";
	public static String GET_TL_E_RTVSHIPMENT_UPDT="UPDATE TL_E_RTVSHIPMENT SET PROCESSFLAG='9', FILENAME=?,PROCESSDATE=sysdate where TRANSID= ?";
	public static String GET_TL_E_LOADSHIP_UPDT="UPDATE TL_E_LOADSHIP SET PROCESSFLAG='9', FILENAME=?,PROCESSDATE=sysdate where TRANSID= ?";
	public static String GET_TL_E_ASNGRN_UPDT="UPDATE TL_E_ASNGRN SET PROCESSFLAG='9' , FILENAME=?,PROCESSDATE=sysdate where TRANSID= ?";
	public static String GET_TL_E_INVCHNG_UPDT="UPDATE TL_E_INVMOVE SET PROCESSFLAG='9' , FILENAME=?,PROCESSDATE=sysdate where TRANSID= ?";
	public static String GET_TL_E_ZSTAMSG_UPDT="UPDATE TL_E_RTWGRN RTW SET PROCESSFLAG='9' , FILENAME=? ,PROCESSDATE=sysdate where TRANSID= ?";
	public static String GET_TL_E_LOADSHIP_ERTL_UPDT="UPDATE TL_E_LOADSHIP_ERTL SET PROCESSFLAG='9', FILENAME=? ,PROCESSDATE=sysdate where TRANSID= ?";
	public static String GET_TL_E_LOADSHIP_ERTL_WS_UPDT="UPDATE TL_E_LOADSHIP_ERTL_WS SET PROCESSFLAG='9', FILENAME=? ,PROCESSDATE=sysdate where TRANSID= ?";
	public static String GET_TL_E_ZWS_GRPOVAPI_UPDT="UPDATE TL_E_ASNGRN_WS SET PROCESSFLAG='9' , FILENAME=?,PROCESSDATE=sysdate where TRANSID= ?";
	public static String GET_TL_E_ASNGRN_ECOMGR_UPDT="UPDATE TL_E_ASNGRN_ECOMGR SET PROCESSFLAG='9' , FILENAME=?,PROCESSDATE=sysdate where TRANSID= ?";
    public static String GET_TL_E_RFIDSKU_UPDT="UPDATE TL_E_WSRFIDITEM SET PROCESSFLAG='9' , FILENAME=?,PROCESSDATE=sysdate where TRANSID= ?";
	public static String GET_TL_E_RFIDASN_UPDT="UPDATE tl_e_WSRFIDASN SET PROCESSFLAG='9' , FILENAME=?,PROCESSDATE=sysdate where TRANSID= ?";
	public static String GET_TL_E_RFIDASNCLOSE_UPDT="UPDATE tl_e_WSRFIDASNCLOSE SET PROCESSFLAG='9' , FILENAME=?,PROCESSDATE=sysdate where TRANSID= ?";
	public static String GET_TL_E_RFIDLOC_UPDT = "UPDATE TL_E_WSRFIDLOCATION SET PROCESSFLAG='9' , FILENAME=?,PROCESSDATE=sysdate where TRANSID= ?";
	public static String GET_TL_E_ASNGRN_WD30_UPDT="UPDATE TL_E_ASNGRN_WD30 SET PROCESSFLAG='9' , FILENAME=? ,PROCESSDATE=sysdate where TRANSID= ?";
	
	//added for Baby Chakra E-com orders
	public static String GET_TRANS_E_LOADSHIP_BC="SELECT distinct(TRANSID) FROM TL_E_LOADSHIP_BC WHERE PROCESSFLAG='0' order by TRANSID";
	public static String GET_TL_E_LOADSHIP_BC_HEADER="select distinct HL,LOADID,LOADDATE,WHSEID from TL_E_LOADSHIP_BC where TRANSID=?";
	public static String GET_TL_E_LOADSHIP_BC_DATA="select distinct HL,EBELN,EBELP,MATNR,MENGE,LPNNO,MSTCARTON from TL_E_LOADSHIP_BC where TRANSID=?";
	public static String GET_TL_E_LOADSHIP_BC_UPDT="UPDATE TL_E_LOADSHIP_BC SET PROCESSFLAG='9', FILENAME=?,PROCESSDATE=sysdate where TRANSID= ?";

	public static String SELECT_STMT="select * from ";
	public static String INSERT_STMT="insert into ";
	public static String SELECT_DTYPE_STMT="select * from USER_TAB_COLUMNS where data_type='DATE' and table_name= ";

	public static String GET_ERROR_LOG="select SERIALKEY,WHSEID,PROGRAMNAME,ERRORMESSAGE from TL_ERROR_LOG where EMAIL_ALERT='N'";
	public static String UPDT_ERROR_LOG="update TL_ERROR_LOG set EMAIL_ALERT='Y' where SERIALKEY=?";
	
	/* New queries for TOTE development */
	public static String GET_TRANS_E_LOADTOTE="SELECT distinct(TRANSID) FROM TL_E_TOTELOADSHIP WHERE PROCESSFLAG='0' order by TRANSID";
	public static String GET_TL_E_TOTELOADSHIP_HEADER="select distinct LOADID,ACTUALSHIPDATE,WHSEID,DC from TL_E_TOTELOADSHIP where TRANSID=?";
	public static String GET_TL_E_TOTELOADSHIP_DATA="select distinct STORE,MATNR,MENGE from TL_E_TOTELOADSHIP where TRANSID=?";
	public static String GET_TL_E_TOTELOADSHIP_UPDT="UPDATE TL_E_TOTELOADSHIP SET PROCESSFLAG='9', FILENAME=?,PROCESSDATE=sysdate where TRANSID= ?";
}